env:
  matrix:
  - TRAVIS_PYTHON_VERSION="2.7" BUILD_DOCS=1 COVERALLS=1
  - TRAVIS_PYTHON_VERSION="3.5" BUILD_DOCS=0 COVERALLS=0
  - TRAVIS_PYTHON_VERSION="3.6" BUILD_DOCS=0 COVERALLS=0
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"
  - secure: wuv2O1M29pkfAjPbOK1MetIf3teDrG4VTepDOps2YFLMzcoJBlJeTqEneVcHb/q2dz5SefjxQQrbLjgZNOURiS1IT2z24srNDPbp8OAsv9nsqAGZO40eWecCRa+u+P+Wh0pZ8urz/ptTir0qFIQ/yz5hoEPx4ScktHkn23V+/fM=
os:
- linux
- osx
sudo: false
filter_secrets: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- echo "Build on $TRAVIS_OS_NAME for Python $TRAVIS_PYTHON_VERSION, $TRAVIS_TAG"
- |
  if [[ "$TRAVIS_TAG" == v* ]]; then
    export BUILD_STR=""
  else
    export BUILD_STR="dev"
  fi
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda create -n _testing python=$TRAVIS_PYTHON_VERSION
- source activate _testing
- conda install -q conda-build=3.0 anaconda-client coverage sphinx
- conda install -q numpy=1.11
- pip install coveralls
- conda info -a && conda list

script:
- conda build -q .conda-recipe -c landlab --old-build-string
- |
 if [[ "$BUILD_DOCS" == "1" && "$TRAVIS_OS_NAME" == "linux" ]]; then
   conda install -q terrainbento --use-local -c $(dirname $(conda build --output ./.conda-recipe/ --old-build-string))
   (cd docs && make html)
 fi
virtualenv:
  system_site_packages: false
after_success:
- if [[ "$COVERALLS" == "1" ]]; then coveralls; fi
