{% set name = "terrainbento" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

source:
  path: ..

requirements:
  build:
    - setuptools
    - python
    - numpy 1.11.*
    - scipy

  run:
    - python
    - numpy >=1.11,<1.14
    - scipy
    - nose
    - numpydoc
    - six
    - pyyaml
    - landlab

test:
  requires:
    - terrainbento
    - numpy <1.14
    - scipy
    - numpy
    - pyyaml

build:
  number: 0
  string: {{ environ.get('BUILD_STR', '') }}
