{% set name = "terrainbento" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

source:
  path: ..

requirements:
  build:
    - setuptools
    - python

  run:
    - python
    - numpy
    - scipy
    - sympy
    - six
    - pyyaml
    - pytest
    - landlab >=1.3

test:
  requires:
    - terrainbento
    - pytest
    - pytest-cov
    - pytest-runner
  commands:
    - pytest --pyargs landlab --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

build:
  number: 0
  string: {{ environ.get('BUILD_STR', '') }}
