{% set name = "terrainbento" %}
{% set data = load_setup_py_data() %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

source:
  path: ..

requirements:
  build:
    - setuptools
    - python

  run:
    - python
    - numpy
    - scipy
    - dill
    - six
    - pyyaml
    - landlab

test:
  requires:
    - terrainbento
    - nose
    - numpydoc

build:
  number: 0
  string: {{ environ.get('BUILD_STR', '') }}
